<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
	https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>com.secureagent</groupId>
	<artifactId>secure-agent</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>SecureAgent</name>
	<description>Security Agent Project</description>

	<properties>
		<maven.compiler.release>11</maven.compiler.release>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.14.0</version>
		</dependency>

		<!-- Npcap을 Java에서 사용할 수 있게 해주는 핵심 라이브러리 -->
		<dependency>
			<groupId>org.pcap4j</groupId>
			<artifactId>pcap4j-core</artifactId>
			<version>1.8.2</version>
		</dependency>

		<!-- TCP, UDP, IPv4, IPv6 등의 패킷을 Java 객체로 변환 -->
		<dependency>
			<groupId>org.pcap4j</groupId>
			<artifactId>pcap4j-packetfactory-static</artifactId>
			<version>1.8.2</version>
		</dependency>

		<!-- SLF4J 로그 출력 구현체 -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.26</version>
		</dependency>

	</dependencies>

	<build>
    <plugins>
        <!-- Java 11로 컴파일 -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.13.0</version>
            <configuration>
                <release>11</release>
            </configuration>
        </plugin>

        <!-- 외부 라이브러리까지 포함한 실행 가능한 JAR 생성 -->
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.6.2</version>

            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>

                    <configuration>
                        <createDependencyReducedPom>false</createDependencyReducedPom>

                        <filters>
                            <filter>
                                <artifact>*:*</artifact>
                                <excludes>
                                    <exclude>META-INF/*.SF</exclude>
                                    <exclude>META-INF/*.DSA</exclude>
                                    <exclude>META-INF/*.RSA</exclude>
                                </excludes>
                            </filter>
                        </filters>

                        <transformers>
                            <transformer implementation=
                                "org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>

                            <transformer implementation=
                                "org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">

                                <mainClass>com.secureagent.AgentMain</mainClass>
                            </transformer>
                        </transformers>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>

</project>